scripts/fixtures.sql

run this before deploying this PR:
```sql
UPDATE oidc_clients
SET post_logout_redirect_uris = '{"https://signup-development.api.gouv.fr"}'
WHERE id = 1;
```

fix: unknown callback url

---

src/views/join-organization.ejs

"Votre Organisation" --> "Rejoindre une organisation"

Change title

---

src/views/join-organization.ejs

Add a mtm campaign for some additionnal and anonymous tracking

Update annuaire link

---

src/managers/user.js

Mesure temporaire pour lutter contre les délais de mails Sendinblue

Allongement validité code confirmation

---

deploy.sh

Rule 2 from The Joel Test
Ref https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/

feat: introduce deploy.sh

---

scripts/fixtures.sql

cf https://github.com/etalab/admin_api_entreprise/issues/687

feat: add URIs for Docker dev API Part/Ent

---

src/views/join-organization.ejs

feat: update insee downtime warning message

---

package-lock.json
package.json
test/is-personal-email.test.js

this commit should be reverted when
https://github.com/131/node-tld/pull/10 is merged.

fix: unable to subscribe user when domain equals tld

---

scripts/fixtures.sql

- Add profile scope
- Add a second redirect URI

Update CD12 configuration

---

scripts/fixtures.sql

Updated redirect_uris for oidc_clients 8 - BaseProjectSIDDEE

Updated redirect_uris for oidc_clients 8

---

scripts/fixtures.sql

Ajout des URLs de test pour l'Annuaire des collectivités

---

.gitignore
installation.md

Objectif : faciliter l'installation sur mac os x

Installation locale sur Mac

---

src/managers/organization.ts

refactor: reduce lexicographical complexity + detect error from

---

scripts/fixtures.sql

Add test configuration for ANCT uMap instance

---

scripts/fixtures.sql

Bad changes previously..
Ref https://github.com/etalab/admin_api_entreprise/issues/1128

Update fixtures for Entreculier

---

scripts/fixtures.sql

Needed to create user in our side
Ref https://github.com/etalab/admin_api_entreprise/issues/1134

API Entreculier: add profile/phone to scope foir fixtures

---

scripts/fixtures.sql

Ah mais oui, il faut pouvoir travailler en local aussi !  Promis c'est la der

Update sso-opérateur fixtures.sql

---

scripts/fixtures.sql

Pour https://espace-demande.dev.incubateur.anct.gouv.fr, nous avons besoin d'accès pour la preprod et le dev afin de tester MonComptePro

Update fixtures.sql for Espace sur Demande (24)

---

scripts/fixtures.sql

Nous avons besoin d'adapter un peu notre fonctionnement et ça requiert de modifier les callbacks autorisés

Petites corrections pour Espace sur Demande

---

scripts/fixtures.sql

🇫🇷 
Bonjour,
On (start-up d'état Données & Territoires de l'incubateur de l'ANCT) souhaiterait intégrer MonComptePro à un de nos projets pour identifier certains de nos utilisateurs.
La première étape que j'ai identifiée est de créer un client oidc de test pour notre projet, ce que j'ai fait dans cette PR.
N'hésitez pas à me dire si j'ai oublié quelque chose pour commencer à avancer sur l'intégration. 🙂 Merci beaucoup !
🇬🇧 
Hello,
We (state start-up Données & Territoires of ANCT incubator) would like to integrate MonComptePro to one of our projects to identify some of our users.
The first step I identified is to create a test oidc client for our project, which I have done in this PR.
Please let me know if I forgot anything or if there is anything else I should do to get started with the …

chore: add catalogue indicateurs test oidc client

---

README.md

Closes https://github.com/betagouv/moncomptepro/issues/352

Replace datapass-staging to staging.datapass

---

scripts/fixtures.sql

I just want to experiment Grist authentication locally using the test environment.

Add localhost for Grist

---

scripts/fixtures.sql

Dans l'idée de débrancher notre couche de SSO expérimental, je voudrais brancher le pad de staging directement sur MCP de préprod.

Add fixtures for pad numérique

---

.editorconfig

chore: add .editorconfig file for consistent coding styles

---

.github/workflows/end-to-end.yml
.github/workflows/fixtures.yml
.github/workflows/test.yml

ci(github): update to actions/checkout@v4

---

.github/workflows/end-to-end.yml
.github/workflows/fixtures.yml
.github/workflows/test.yml
package.json

chore(node): update to node 20.x

---

.github/workflows/end-to-end.yml
installation.md

ci(github): use ghcr.io/betagouv/moncomptepro-test-client image

---

src/views/partials/card-button-container.ejs

</p>
--- 
\from @Anais-Tailhade 
User might get stuck if they can't change email on the verification page.

fix(verify-email): back button should come back to the start

---

src/views/home.ejs
src/views/partials/maintenance.ejs
src/views/user/start-sign-in.ejs

This reverts commit 954d252cf1c8dc0f2e8c77da06bd7ba4dde4560a.

Revert "feat: display maintenance alert"

---

src/types/moderation.d.ts

feat(types): add ticket_id on Moderation interface

---

README.md

Closes https://github.com/betagouv/moncomptepro/issues/457

FIX invalid urls

---

src/services/organization.ts
test/organization.test.ts

Contact data from annuaire education nationale are not accurate enough

fix: temporarily consider private schools as generic private org

---

src/views/mails/unable-to-auto-join-organization.ejs
src/views/user/unable-to-auto-join-organization.ejs

TODO : on revert la semaine pro.

removing time for moderation delay

---

src/views/passkeys.ejs
src/views/personal-information.ejs
src/views/user/join-organization-confirm.ejs
src/views/user/personal-information.ejs

Here a few small commits for tiny label changes and other misc things for better UX for everyone (everything explained in the commit messages as usual!)

Tiny accessibility changes

---

.github/CODEOWNERS

So the idea is I want to track pull requests where front-end changes occur to make sure accessibility problems are not added (in addition to future automated tests I'll add), without having to subscribe to the whole repo and get back-end code PR notifications.
testing this github feature thanks to @revolunet!

Add pull requests frontend notifications for me through codeowners file

---

src/middlewares/rate-limiter.ts

feat(middlewares): boost api rate limite to 42 ❤️‍🔥

---

.github/workflows/end-to-end.yml

chore(deps): bump falti/dotenv-action to 1.1.1

---

.github/workflows/end-to-end.yml

chore(deps): bump cypress-io/github-action to 6.6.1

---

.github/workflows/end-to-end.yml

chore(deps): bump actions/upload-artifact to v4

---

cypress/README.md
docker-compose.yml
scripts/run-test.sh
scripts/test.sh

Here a couple things after @rdubigny feedback:
- actually use the good docker compose…
- add a `prepare` command that handles db reset/fixtures/env/starting the server for us. useful for manual testing

Better test script

---

scripts/test.sh

fix: test script didnt gather env vars dynamically

---

.github/workflows/end-to-end.yml
.github/workflows/fixtures.yml
.github/workflows/test.yml

</p>
---
Extracted from https://github.com/betagouv/moncomptepro/pull/536

ci(github): bump ubuntu to 22.04

---

.prettierignore

chore(prettier): ignore built folder

---

.prettierignore
package-lock.json
package.json

<h1 align="center">Update DSFR</h1>
</p>

bump-@gouvfr/dsfr-to-1.11.0

---

.github/workflows/end-to-end.yml
.github/workflows/fixtures.yml
.github/workflows/test.yml

I was wrong sry 
Reverts betagouv/moncomptepro#548

Revert "Revert "ci(github): bump ubuntu to 22.04""

---

src/index.ts

feat(sentry): pass the DEPLOY_ENV as environment

---

src/services/organization.ts

cf. https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1024

feat: update is service public

---

src/views/connection-and-account.ejs
src/views/manage-organizations.ejs
src/views/user/join-organization.ejs
src/views/user/organization-suggestions.ejs
src/views/user/select-organization.ejs

feat(views): too much space in p tiles

---

package-lock.json
package.json

Upgrade @gouvfr/dsfr package from version 1.11.2 to 1.12.1.
</p>

RD: update package @gouvfr/dsfr to 1.12.1

---

.github/CODEOWNERS

Reverts numerique-gouv/moncomptepro#616

Revert "chore: rdubigny is a global owner"

---

.github/workflows/end-to-end.yml

ci(github): an artifact per e2e test

---

src/controllers/user/update-personal-informations.ts
src/services/custom-zod-schemas.ts
src/views/personal-information.ejs
src/views/user/personal-information.ejs

Add constraint rules (back & front) and message for the field "job" :
</p>

RD: add constraint in front & back

---

assets/css/searchable-select.css
assets/js/app.js
assets/js/autosubmit-form.js
assets/js/collapse-sidemenu.js
assets/js/confirm-password.js
assets/js/confirm.js
assets/js/did-you-mean.js
assets/js/fetch-organization-info.js
assets/js/go-back.js
assets/js/matomo.js
assets/js/modules/load-bar.js
assets/js/password-feedback.js
assets/js/searchable-select.js
assets/js/show-password.js
assets/js/submit-tile-forms.js
assets/js/webauthn-registration.js
postcss.config.cjs

<h1 align="center">𝖏𝖚𝖘𝖙 𝖋𝖔𝖗 𝖞𝖔𝖚𝖗 𝖕𝖑𝖊𝖆𝖘𝖚𝖗𝖊</h1>
</p>

RD: run command prettier on all files

---

src/views/help.ejs

feat(help): add xkcd caption

---

.github/workflows/end-to-end.yml
cypress/e2e/delete_account.cy.js
cypress/fixtures/delete_account.sql
src/connectors/brevo.ts
src/controllers/user/delete.ts
src/managers/user.ts
src/views/mails/delete-account.ejs

RD: send mail notification when user delete his account

---

.github/workflows/end-to-end.yml
cypress/e2e/delete_totp.cy.js
cypress/fixtures/delete_totp.sql
src/connectors/brevo.ts
src/controllers/totp.ts
src/managers/user.ts
src/views/mails/delete-free-totp.ejs

<p align="center"><img src="https://media.giphy.com/media/8FNlmNPDTo2wE/giphy.gif?cid=790b7611gmcmjqabl0x780kwa9gjnih0e4ybhp2pcqcwp4n0&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>

RD: send email when TOTP is deleted + add test

---

cypress/e2e/delete_totp.cy.js
cypress/fixtures/delete_totp.sql
src/connectors/brevo.ts
src/controllers/main.ts
src/controllers/totp.ts
src/managers/user.ts
src/views/mails/delete-2fa-protection.ejs

<h1 align="center">💀  🇳  🇴 &nbsp;&nbsp;&nbsp;🇲  🇴  🇷  🇪  &nbsp;&nbsp;&nbsp; 🇹 🇼 🇴  &nbsp;&nbsp;&nbsp;🇫  🇦  💀</h1>
<p align="center"><img src="https://media.giphy.com/media/pmcakBV6ukolp5YZAv/giphy.gif?cid=ecf05e4759vl1d2n5feizfruvgj68k3r6gsl61ur02jscyjt&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>

RD: send mail when user disable 2fa protection

---

src/connectors/brevo.ts
src/controllers/webauthn.ts
src/managers/user.ts
src/views/mails/delete-access-key.ejs

<p align="center"><img src="https://media.giphy.com/media/DNGyb0ICWl0Mb2Waoq/giphy.gif?cid=790b7611vdiwp44516ln8zb2djtqqz3hv9czj7hipljpesjb&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>

RD: Send email when user deletes access key to their account

---

src/connectors/brevo.ts
src/controllers/webauthn.ts
src/managers/user.ts
src/views/mails/add-access-key.ejs

<p align="center">Send email when user adds access key to their account</p>
</br>
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHVhYzZkcGZrdzRsZWtsbHV2Yml2Z2lvOXlucnM5dDk1NnlxaDJ5bCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/8Py8gIK84esy7jkXKO/giphy.gif"></p>
</br>

RD: Send email when user adds access key to their account

---

.github/workflows/end-to-end.yml
cypress/e2e/update_totp_application.cy.js
cypress/fixtures/update_totp_application.sql
src/connectors/brevo.ts
src/managers/totp.ts
src/managers/user.ts
src/views/authenticator-app-configuration.ejs
src/views/mails/update-totp-application.ejs

<p align=center>𝑀𝑒 𝒶𝒻𝓉𝑒𝓇 𝓉𝒽𝑒 "𝑒𝒶𝓈𝓎" 𝓉𝒾𝒸𝓀𝑒𝓉 𝑔𝒾𝓋𝑒𝓃 𝒷𝓎 @rdubigny</p>
<p align="center"><img src="https://media.giphy.com/media/dmjCMRYLNG0DK/giphy.gif?cid=790b76116mcaydkaf17vb6e9utexkf4r6rvxr4slkv1k8ruu&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>

RD: send email update totp app

---

package-lock.json
package.json

chore(deps): update to node-pg-migrate@7.6.1

---

src/controllers/main.ts
src/managers/session/authenticated.ts
src/managers/user.ts
src/views/mails/update-personal-data.ejs

refactor: ensure to send an email when a change occurred

---

src/controllers/main.ts

chore: remove more ruby logs

---

migrations/1723123440097_remove-same-null-verified-email-domain.cjs

feat(database): remove same null verified email domain

---

migrations/1721662773865_update-verification-type.cjs
package-lock.json
package.json

chore(deps): update to prettier@3.3.3

---

Dockerfile
package.json

chore(deps): update to npm@10.8.2

---

package-lock.json
package.json

chore(deps): update to cypress@13.13.2

---

.github/workflows/test.yml
package.json
src/controllers/user/verify-email.ts
src/managers/browser-authentication.ts
src/middlewares/user.ts
src/services/owasp-password-strength-tester.ts
tsconfig.json

chore(pkg): add script test:type-check

---

src/views/partials/footer.ejs

<p align="center"><img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDk4dXpkd2NyamM4cm01OTJpaGFpN2xxczg3aGh2ZXIxa2s5dXo5cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/GiT2qkC092xAKknPRp/giphy.gif"></p>

refacto: delete link and title disconnect footer

---

tsconfig.json

chore(tsc): add noFallthroughCasesInSwitch option

---

src/connectors/postgres.ts
src/controllers/api.ts
src/controllers/main.ts
src/controllers/organization.ts
src/controllers/user/choose-sponsor.ts
src/controllers/user/select-organization.ts
src/index.ts
src/middlewares/rate-limiter.ts
src/middlewares/user.ts
src/routers/api.ts
src/services/hash-to-postgres-params.ts
src/services/json-parse-with-date.ts
src/services/oidc-account-adapter.ts
tsconfig.json

chore(tsc): add noUnusedParameters option

---

migrations/1724327131305_update-ticket-id.cjs
src/managers/organization/join.ts
src/repositories/moderation.ts
src/types/moderation.d.ts

feat(database): ticket id are strings

---

package-lock.json
package.json
src/controllers/user/official-contact-email-verification.ts

:heavy_plus_sign: use await-to-js to deal with business errors flow

---

src/connectors/crisp.ts

:pirate_flag: (crisp): add delay hack

---

src/views/help.ejs
src/views/partials/header.ejs

<p align="center">j'ai pas les mots</p>
<p align="center"><img src="https://media.giphy.com/media/26BGqofNXjxluwX0k/giphy.gif?cid=790b7611lv6mq06ek7m7uh8k8c2w12sbb7lcln9dt7sz15q0&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>

chore(wording): rename MCP to PC in header & help

---

assets/js/crisp.js
src/index.ts
src/views/partials/head.ejs

feat: help adding crisp widget

---

assets/js/crisp.js
src/index.ts
src/views/partials/head.ejs

add crisp widget

---

cypress/e2e/join_with_code_sent_to_official_contact_email/index.cy.ts
cypress/e2e/join_with_official_contact_email/index.cy.ts

<p align="center"><img src="https://media.giphy.com/media/UV4liSdOaKdw3V9HGI/giphy.gif?cid=790b7611zc2uhcpkzlvyujw3vnnmavtjaltug54bmvu38o7f&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>

fix(ci): add missing step in test

---

scripts/fixtures.sql

Reverts numerique-gouv/moncomptepro#715

Revert "add new domains for ASTREA in preprod"

---

.github/dependabot.yml

</p>
---
Linked to https://github.com/betagouv/moncomptepro/pull/537

chore(dependabot): update npm packages too

---

assets/js/matomo.js
src/views/partials/head.ejs
src/views/user/2fa-sign-in.ejs
src/views/user/sign-in.ejs
src/views/user/sign-up.ejs

Add Tag Manager and some id's to track event click

Add Tag Manager from Matomo

---

cypress/support/a11y/checkA11y.ts
cypress/support/a11y/checks/has-page-title.ts
cypress/support/commands.ts
cypress/support/get-from-email.ts
package.json
scripts/import-accounts-coop.ts
scripts/import-accounts.ts
scripts/import-domains.ts
scripts/run-sql-script.ts
scripts/update-organizations-info.ts
test/epoch-time.test.ts
test/is-expired.test.ts
test/organization.test.ts
tsconfig.json

</p>
---
It seems like typescript is not really checking all the files :eye: 
[On can see all the remaining errors](https://github.com/numerique-gouv/moncomptepro/actions/runs/11075883440/job/30777783388?pr=712#step:6:11)

chore(tsc): cover the whole project

---

.github/workflows/end-to-end.yml
cypress.config.ts
cypress/support/e2e.ts
docker-compose.yml
package-lock.json
package.json

extracted from https://github.com/numerique-gouv/moncomptepro/pull/650

chore: add maildev

---

packages/email/.storybook/ChangeView.tsx
packages/email/.storybook/SendEmailFormWebComponent.tsx

refactor(email): use static blocks instead of static fn

---

src/connectors/mail.ts
src/managers/user.ts

</div>
--- 
Thanks GPT for suggesting this undocumented brevo header :robot:

feat(email): use X-Mailin-Tag to pass a brevo tag

---

packages/email/src/components/Badge.tsx
packages/email/src/components/Button.tsx
packages/email/src/components/Em.tsx
packages/email/src/components/index.ts
packages/email/src/components/style.ts

</div>
---
Extract from https://github.com/numerique-gouv/moncomptepro/pull/788 and https://github.com/numerique-gouv/moncomptepro/pull/789

feat(email): more email components

---

src/views/mails/unable-to-auto-join-organization.ts

fix(email): use the proconnect banner on moderation mails

---

src/connectors/api-annuaire-service-public.ts
test/api-annuaire-service-public-data/one-mairie.json
test/api-annuaire-service-public-data/two-mairies.json

fix(connectors): parse the annuaire adresse field

---

packages/email/src/DeleteAccount.tsx

fix(email): delete account link label

---

cypress/e2e/join_with_official_contact_email/env.conf
cypress/e2e/join_with_official_contact_email/fixtures.sql
cypress/e2e/join_with_official_contact_email/index.cy.ts
cypress/e2e/set_info_after_account_provisioning/index.cy.ts
cypress/e2e/signin_with_email_verification/index.cy.ts
cypress/e2e/signin_with_email_verification_renewal/index.cy.ts
cypress/e2e/signin_with_magic_link/index.cy.ts
cypress/e2e/signin_with_totp/index.cy.ts
cypress/e2e/signup_entreprise_unipersonnelle/index.cy.ts
cypress/support/get-from-email.ts
packages/email/src/VerifyEmail.stories.tsx
packages/email/src/VerifyEmail.tsx
packages/email/src/index.ts
src/connectors/brevo.ts
src/managers/user.ts

feat(email): add verify email smtp email

---

package.json

chore: update to latest node@22

---

src/types/email-domain.d.ts

</p>
---
Note: I sorted the type alphabetically

feat(types): add refused verification type

---

.github/workflows/end-to-end.yml
cypress/e2e/signin_with_right_acr/index.cy.ts
docker-compose.yml

Reverts numerique-gouv/moncomptepro#842

Revert "fix(docker): fix proconnect-test-client version"

---

installation.md

Here comes a lil documentation about [changesets](https://github.com/changesets/changesets)

docs(README): add changeset documentation

---

src/config/env.zod.ts
src/index.ts
src/middlewares/connection-count.ts
test/env.zod.test.ts

fix(www): silence oidc invalid requests

---

package-lock.json
src/connectors/mail.ts

https://trello.com/c/DLtIIsjh/355-environnement-de-sandbox-ajouter-un-test-dans-le-sujet-des-emails-envoy%C3%A9?filter=member:benoitserrano1

feat: add prefix for mail in sandbox

---

.github/workflows/release.yml
package.json

Linked to https://github.com/changesets/action/issues/203

ci(release): ensure to update package lock after changeset version

---

docker-compose.yml

@douglasduteil and I discovered that maildev didn't work on my mac! We've found this fix, now let's see if it works on all machines!

fix(maildev): add specific port for maildev

---

.changeset/selfish-apes-push.md
packages/core/src/services/suggestion/did-you-mean.test.ts
packages/core/src/services/suggestion/did-you-mean.ts
packages/core/tsconfig.json

fix(core): force node next module compatibility

---

package-lock.json
package.json

chore(deps): update to cypress@13.17.0

---

.changeset/fast-peas-sin.md
packages/core/package.json
packages/core/src/services/email/index.ts
packages/core/src/services/suggestion/index.ts
src/managers/user.ts
src/services/email.ts

refactor(core): only export index.ts files

---

package-lock.json
package.json
packages/core/package.json

chore(deps): update to tsx@4.19.2

---

.github/workflows/end-to-end.yml
.github/workflows/fixtures.yml
docker-compose.yml
scripts/create-anonymized-copy-of-database.sh

chore(deps): update to postgres:15.10

---

src/index.ts

fix(www): ignore Oidc user InvalidRedirectUri

---

cypress/README.md
installation.md

docs(README): add internal dependencies build script

---

.github/labeler.yml
.github/workflows/labeler.yml

ci(github): add auto labeller

---

.changeset/nervous-countries-worry.md
.github/labeler.yml
.github/workflows/test.yml
Dockerfile
package-lock.json
package.json
packages/crisp/package.json
packages/crisp/src/client/fetcher.ts
packages/crisp/src/client/index.ts
packages/crisp/src/index.ts
packages/crisp/src/router/conversation.e2e.test.ts
packages/crisp/src/router/conversation.ts
packages/crisp/src/router/index.ts
packages/crisp/src/router/operators.e2e.test.ts
packages/crisp/src/router/operators.ts
packages/crisp/src/types.ts
packages/crisp/test/config.ts
packages/crisp/test/dotenv.ts
packages/crisp/test/expect.ts
packages/crisp/tsconfig.json
packages/crisp/tsconfig.lib.json
src/connectors/crisp.ts

feat(crisp): move @douglasduteil/crisp to @gouvfr-lasuite/proconnect.crisp

---

.changeset/slimy-roses-swim.md
package-lock.json
packages/core/package.json
packages/core/src/services/email/isAFreeDomain.ts
packages/core/src/services/suggestion/did-you-mean.ts

</div>
---
Old software needs old stuff :(

chore(core): publish common js files :sad:

---

package-lock.json
package.json

chore(deps): update to helmet@8.0.0

---

packages/crisp/package.json

</div>
---
The support team said blocked Frodon Sacquet ...

chore(crisp): disable test

---

.changeset/clever-clocks-know.md
packages/core/package.json

chore(core): add types versions to package.json

---

src/controllers/interaction.ts
src/types/oidc-provider.d.ts

 refactor: add types to interaction context params 

---

cypress/e2e/signup_entreprise_unipersonnelle/index.cy.ts

e2e: use douglasduteil as test subject

---

cypress/e2e/signin_with_right_acr/index.cy.ts

e2e(signin_with_right_acr): no self asserted

---

.github/workflows/end-to-end.yml
.github/workflows/fixtures.yml
.github/workflows/release.yml
.github/workflows/test.yml
package-lock.json
package.json

chore(pkg): use node@v22.13.1

---

.github/dependabot.yml

chore(dependabot): match the latest version

---

.changeset/happy-years-care.md
package-lock.json
package.json
packages/core/package.json
packages/crisp/package.json
packages/debounce/package.json
packages/email/package.json
packages/identite/package.json
packages/insee/package.json

chore(pkg): depend on the shared tsconfig dependency

---

.changeset/famous-hats-dream.md
package-lock.json
packages/identite/package.json
packages/identite/src/errors/index.ts
packages/identite/src/managers/organization/force-join-organization.test.ts
packages/identite/src/managers/organization/force-join-organization.ts
packages/identite/src/managers/organization/index.ts
packages/identite/src/repositories/organization/index.ts
packages/identite/src/repositories/organization/link-user-to-organization.test.ts
packages/identite/src/repositories/organization/link-user-to-organization.ts
packages/identite/src/repositories/organization/upsert.ts
packages/identite/src/repositories/user/find-by-id.ts
src/config/errors.ts
src/controllers/api.ts
src/controllers/organization.ts
src/controllers/totp.ts
src/controllers/user/edit-moderation.ts
src/controllers/webauthn.ts
src/managers/moderation.ts
src/managers/oidc-client.ts
src/managers/organization/join.ts
src/managers/organization/main.ts
src/managers/organization/official-contact-email-verification.ts
src/managers/user.ts
src/managers/webauthn.ts

refactor: extract force join organization

---

assets/js/matomo.js

<p align="center"><img src="https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXdxNzR4dmV5OGRvNWtjc3Bnb2ZjY2Q5MWtoNTRmdWlwajNxb3R5eCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/9ADoZQgs0tyww/giphy.gif"></p>

chore(matomo): Add generic Matomo script to fix stats

---

src/views/connection-and-account.ejs

<p align="center"><img src="https://media.giphy.com/media/gjgWQA5QBuBmUZahOP/giphy.gif?cid=82a1493b74lzcdk2l7j74m2v3c5x4nogldg7us2p3fx5aap3&ep=v1_gifs_trending&rid=giphy.gif&ct=g"></p>

chore(2fa): add missing informations 2fa cards

---

cypress/e2e/signin_with_right_acr/index.cy.ts

<p align="center"><img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDNzMDNkMXAxNTR2cXZ6dHhlODZsbWlhYjRjcGFhcjNhc3YzYmhoMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3orieUe6ejxSFxYCXe/giphy.gif"></p>

fix(typo): fix typo in test description

---

cypress/README.md

<p align="center"><img src="https://media.giphy.com/media/hoFGPAQYRBxjW/giphy.gif?cid=790b7611ktz0aeeolnidf4cjdx4j3ksar1jq39exq5iajj9i&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>

docs(cypress): add doc to generate cypress record

---

package.json

chore(pkg): avoid deleting dist in node_modules

---

src/views/_layout.ejs
src/views/partials/skiplinks.ejs

<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTV2emQ2NTZmZ2hzbGQ1OXR1czdwN3ZycWxtbmFnMjd1ejBqbm8ydCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/aYzxVt2lMrZXW/giphy.gif"></p>

fix(a11y): add "formulaire de connexion" to skiplinks & create dedicated component

---

tsconfig.json

chore(tsconfig): ensure to include cypress files

---

src/connectors/api-sirene.ts

fix(connectors): add HTTP_CLIENT_TIMEOUT

---

src/views/partials/password-input-messages.ejs
src/views/user/sign-up.ejs

<p align="center"><img src="https://media.giphy.com/media/gjgWQA5QBuBmUZahOP/giphy.gif?cid=82a1493b3rozq3ctjnuj5vfanj0w8bp7zw4ubsc1es6h0gxt&ep=v1_gifs_trending&rid=giphy.gif&ct=g"></p>

fix(a11y): add span for help with entering password

---

src/controllers/api.ts
src/index.ts
src/managers/organization/join.ts
src/routers/api.ts

fix(index): log up to 3 level of errors

---

src/views/partials/password-input-messages.ejs

This reverts commit d507e6082a95bcefe53400cfbfeb5f96fdf7b1f1.
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExb3JpNWlhYThkMHF3aDU5bm1qazBvZzRidWRsbnF4aXA3dTlkdjl4dCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3ohA2ZD9EkeK2AyfdK/giphy.gif"></p>

Revert "fix(a11y): delete useless span"

---

.github/workflows/end-to-end.yml
cypress/README.md
cypress/support/e2e.ts

chore(e2e): do not always slow down cypress videos

---

src/views/partials/footer.ejs

<p align="center"><img src="https://media.giphy.com/media/3o7TKyhhUW9gVsHiF2/giphy.gif?cid=790b7611ctj5e76tkyez25j7ctecvdyesnfvyxslhjn0d70n&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>

refactor(a11y): add blank and title on link in footer

---

packages/identite/src/managers/franceconnect/openid-client.ts

feat(franceconnect): force reauth

---

src/views/configuring-single-use-code.ejs
src/views/error.ejs
src/views/personal-information.ejs
src/views/user/join-organization.ejs
src/views/user/official-contact-email-verification.ejs
src/views/user/verify-email.ejs

<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXA0ZXhpcXJqamphOHE0aXcxNjQxMW1raWJqN2ZlaTFzdjFiNmpnYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/LXfpI3nNbfCm91llsA/giphy.gif"></p>

feat(link): add blank attribute to links & deletes icon

---

assets/css/home-tile.css

feat(home): remove an extra background behind the svg

---

assets/js/matomo.js

<p align="center"><img src="https://media.giphy.com/media/gH6jM4xcOCEyRCYKpT/giphy.gif?cid=790b76115bzzolv1sci5lf5291n8bq5en0tc4lqqqze16mcx&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>

feat(tracking): add Matomo tag manager code

---

cypress/e2e/signin_with_right_acr/index.cy.ts

test: update to latest test client image

---

src/config/errors.ts
src/controllers/user/franceconnect.ts

feat: add oidc franceconnect error

---

src/instrument.ts

chore(sentry): capture console

---

packages/testing/package.json
packages/testing/src/api/routes/oidc.franceconnect.gouv.fr/index.ts
packages/testing/tests/integration.test.ts
packages/testing/tsconfig.json

chore: correct typescript tests

---

package-lock.json
package.json

chore(pkg): update to node@22.15 and npm@11.3

---

.github/workflows/fixtures.yml
compose.yml

</div>
\linked to https://github.com/numerique-gouv/proconnect-identite/pull/959

chore(deps): update to postgres:16.8

---

.github/workflows/fixtures.yml
compose.yml

</div>
\linked to https://github.com/numerique-gouv/proconnect-identite/pull/959 #1210

chore(deps): update to postgres:16.9

---

packages/crisp/package.json
packages/debounce/package.json
packages/debounce/src/api/single-validation.test.ts
packages/entreprise/package.json

refactor(debounce): replace mocha with node:test

---

.github/dependabot.yml

chore(dependabot): add docker

---

.github/dependabot.yml

chore(dependabot): add docker-compose

---

.github/dependabot.yml

chore(dependabot): add scalingo limitations

---

compose.yml

<div align=center>
</div>
--- 
Something is wrong with the latest test clients images ?

🥶 fix(docker): use freezed test client version

---

scripts/fixtures.sql

chore(fixtures): update showcase url

---

.env.development
.env.test
.github/workflows/end-to-end.yml
.github/workflows/fixtures.yml
src/config/env.zod.ts
test/env.zod.test.ts

chore(env): SMTP_URL is mandatory for the env var

---

src/index.ts

chore: log the mode when the app starts

---

.github/workflows/end-to-end.yml
.github/workflows/fixtures.yml
.github/workflows/test.yml

ci(github): use ubuntu-latest

---

src/views/user/welcome-dirigeant.ejs

fix(welcome): big check img

---

packages/testing/src/api/routes/entreprise.api.gouv.fr/mandataires_sociaux/552032534.json

fix(testing): wrong birthday for ulysse

---

compose.yml
cypress/e2e/signin_from_proconnect_federation_client/index.cy.ts
cypress/e2e/signin_from_standard_client/index.cy.ts
cypress/e2e/signin_with_certification_dirigeant/index.cy.ts
cypress/e2e/signin_with_legacy_scope/index.cy.ts
cypress/e2e/signin_with_right_acr/index.cy.ts
cypress/support/commands.ts

chore(docker): use latest proconnect-test-client version

---

assets/css/dsfr.css

feat: 1px fix on FranceConnect button

---

packages/testing/src/api/routes/entreprise.api.gouv.fr/mandataires_sociaux/792713778.json

fix(testing): wrong birthday for stevens

---

packages/entreprise/src/testing/seed/insee/siret/00557246600026.ts
packages/entreprise/src/testing/seed/insee/siret/20007184300060.ts
packages/entreprise/src/testing/seed/insee/siret/21920023500014.ts
packages/entreprise/src/testing/seed/insee/siret/32122785200019.ts
packages/entreprise/src/testing/seed/insee/siret/41816609600069.ts
packages/entreprise/src/testing/seed/insee/siret/43841606700017.ts
packages/entreprise/src/testing/seed/insee/siret/78824266700020.ts
packages/entreprise/src/testing/seed/insee/siret/81104725700019.ts
packages/entreprise/src/testing/seed/insee/siret/82271212100018.ts
packages/entreprise/src/testing/seed/insee/siret/94957325700019.ts
packages/entreprise/src/types/establishment.ts
packages/identite/src/managers/organization/get-organization-info.test.ts
packages/identite/src/mappers/organization/from-siret.ts
packages/testing/src/api/data/people.ts
packages/testing/src/api/routes/entreprise.api.gouv.fr/etablissements/discover.page.tsx
packages/testing/src/api/routes/entreprise.api.gouv.fr/etablissements/index.ts
packages/testing/src/cli/entreprise/etablissements/add.ts

refactor(entreprise): rename entreprise api insee sirene data types

---

container-structure-test.yml

test(docker): wait 5s max for the server to start

---

cypress/e2e/signin_from_proconnect_federation_client/fixtures.sql
cypress/e2e/signin_from_proconnect_federation_client/index.cy.ts
cypress/e2e/signin_from_standard_client/index.cy.ts
packages/identite/src/types/claims.ts
packages/identite/src/types/index.ts
src/services/oidc-account-adapter.ts
src/types/PartialNullable.d.ts

<div align=center>
</div>
---
> [!NOTE] 
> Changes in `cypress/e2e/signin_from_standard_client/index.cy.ts` are not really linked to this PR. I though it easier to read with less CSS path getter in the files

🐛 fix: remove null and empty field in claim

---

src/controllers/main.ts
src/routers/main.ts
src/views/legal-proconnect/accessibility.ejs
src/views/legal-proconnect/cgu.ejs
src/views/legal-proconnect/privacy-policy.ejs
src/views/partials/footer.ejs

<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdWF2aGtqNXRnMzZ5cDF4OXRleHplZjYwb2FtNzR5cG93c215bGhkNiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/QXPB1mCBDTpW4hMjeK/giphy.gif"></p>

chore(legal): create legals routers controllers and views

---

cypress/e2e/set_info_after_account_provisioning/index.cy.ts
cypress/e2e/signin_with_certification_dirigeant/index.cy.ts
cypress/e2e/signup_entreprise_unipersonnelle/index.cy.ts
src/controllers/main.ts
src/controllers/user/update-personal-informations.ts
src/managers/user.ts
src/middlewares/user.ts
src/views/user/personal-information.ejs
src/views/user/welcome-dirigeant.ejs

delete useless job input

---

CONTRIBUTING.md

internal source: https://documentation.beta.numerique.gouv.fr/doc/standards-de-contribution-pc-gQwQpAV4Ro

📝 add CONTRIBUTING.md

---

cypress/README.md

<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMW4yOTU5NWVsd25oZmZpcmZ0MHlnazNkdW05ZTRmbW1vZGU1eng5MSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/YqK4o9txKgn6M/giphy.gif"></p>

✅ Adds manual test documentation for passkey configuration

---

cypress/e2e/signin_with_totp_enrollment/index.cy.ts

<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHFib2FqYTdsc3Nramx5dmxiZ3J2Zjg3aHdvOHM0aTJ0OHkzZGViMSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/YpfGgAkAwHjv67fYgh/giphy.gif"></p>

♻️ refactor access to the mfa choice page in tests

---

.github/workflows/end-to-end.yml
cypress/e2e/quit-organization/fixtures.sql
cypress/e2e/quit-organization/index.cy.ts

<div align=center> <img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXVucW0wODFqemtjeGFkbmV6NzkxcmFud3Ftc3N2d2t6d2ZlMHZtaiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/5FcXjQA6IDr3i/giphy.gif" /> </div>
---
Adding missing quit e2e test

🚥 test(e2e): add quit organization
