proconnect-gouv/proconnect-identite

src/connectors/oidc-account-adapter.js
ie. https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.2
=> feat: sub as a string is more standard

src/configuration.js
Since commit 913627bea9ada172ceaea7e62857148d432eac19 grant is not always defined and following error arrise : TypeError: Cannot read property 'exp' of undefined
=> Fix: Grant can be undefined

src/controllers/interaction.js
Previously in commit 1d3c76f9c1291c6adcbc028dd7cf15ade839d5b9 which
introduces a bunch of modification for the bump oidc-provider v7, there
was in this function conditions on consent prompt.
It is no longer the case, but we currently experienced a lot of 500
error because of an unknown_interaction_name consent.
This commit partially reverts to the previous behaviour (at least for
`consent` prompt, the `login` prompt has been changes too but it is not
changed here, only the `consent` prompt management is restored).
Related https://github.com/betagouv/api-auth/commit/1d3c76f9c1291c6adcbc028dd7cf15ade839d5b9
Related https://sentry.data.gouv.fr/organizations/sentry/issues/13
Related https://mattermost.incubateur.net/betagouv/pl/w71pertnstdtmgjsa7ff5c8axo
=> fix: unknown_interaction_name consent

src/views/partials/header.ejs, src/views/user/magic-link-sent.ejs, src/views/user/sign-in-with-magic-link.ejs, src/views/user/sign-in.ejs, src/views/user/sign-up.ejs, src/views/user/start-sign-in.ejs
Au début j'ai créé la PR car le champ email dans le formulaire de connexion portait deux fois l'élément `id`.  
J'ai supprimé l'`id` surnuméraire et j'ai branché le `label` sur l'id `did-you-mean` qui semblait utilisé par un script intéressant.
Ensuite j'ai fait une passe sur les alternatives des images : 
- toutes les images décoratives : il leur faut un `alt` vide ;
- le logo dans l'en-tête : j'ai mis juste "MonComptePro" dans l'alternative, pas besoin de préciser que c'est le "logo".
=> Amélioration de l'accessibilité

scripts/fixtures.sql
Reorder scope to fit outline doc. 
Dans outline, j'ai cette erreur : "UnauthorizedError: Neither a name or username was returned in the profile parameter, but at least one is required.
J'ai pensé qu'en remettant le scope dans l'ordre attendu par outline, ça pourrait aider.
=> Update fixture.sql for outline scope

src/routers/api.ts, src/routers/main.ts
using urlencoded on / parse the params even for /oauth oidc's routes which uses its own parser.
=> chore: remove oidc warning about double parsing

scripts/fixtures.sql
Add a new redirect_uri to split Keycloak IDPs for MonComptePro
=> fix: CD12 - add new redirect-uri

scripts/fixtures.sql
Bonjour :wave:
Une coquille s'est malencontreusement glissée dans notre (Startup D&T de l'inubateur de l'ANCT) client de test rajouté récemment. 🤦 
Le but de la PR est simplement de corriger l'erreur.
Merci d'avance !
=> fix: typo in anct catalogue callback urls

scripts/fixtures.sql
We'd like to allow fetching profile information from the Grist dev environment, so we can retrieve the family and given name of the users.
Also we'd like to test new callback / sign out URLs related to that development (in draft):
https://github.com/gristlabs/grist-core/pull/717
=> Allowing profile for Grist dev environment

scripts/fixtures.sql
These URL are the ones expected by Grist native OIDC implementation. We expect to deploy it soon.
=> Add new URLs for staging instance of Grist

.github/workflows/end-to-end.yml, docker-compose.yml, installation.md, migrations/1703247171649_add-zammad-ticket-id-on-moderations.js, package-lock.json, src/config/env.ts, src/config/errors.ts, src/connectors/sendZammadMail.ts, src/connectors/sendinblue.ts, src/managers/organization/authentication-by-peers.ts, src/managers/organization/join.ts, src/repositories/moderation.ts
</p>
---
This PR allow moncomptepro to send mail through Zammad.
Note that the ci is doing **real case test** resulting on actual Zammad Tickets on our Zammad. We might want to find a way to use a fake/test zammad instance to reduce the noise on our side.
---
BREAKING CHANGE: Require additional ZAMMAD env variables.
```ini
ZAMMAD_URL=http://zammad/
ZAMMAD_TOKEN=your_zammad_token
```
=> feat: use zammad to send join email

scripts/fixtures.sql
Avec ceci, les gens avec une adresse email en beta.gouv.fr pourront rejoindre le MTE.
TEMPORAIRE.
=> add MTE organization to beta.gouv domain email

scripts/fixtures.sql
This scope is deprecated, we try to remove it in our staging environment.
=> Grist - remove `organizations` scope

src/views/mails/unable-to-auto-join-organization.ejs, src/views/user/unable-to-auto-join-organization.ejs
changer délai moyen de support 3 jours vers 1 jour ouvré.
Cette PR est en vue de tester de raccourcir le délai moyen voir si cela nous ajoute du support à traiter. Vu avec Anaïs : le support sera redirigé vers moi. Si le test est concluant, nous garderons ce délai.
Ceci est en vue de retirer temporairement la notion de délai pour le gros d'Égapro les 5 derniers jours de Février.
=> changer délai moyen 3 jours vers 1 jour ouvré

scripts/fixtures.sql
2 ajouts de type d'organisation au domain_email `yopmail.com` : 
- totalenergies pour une orgnaisation privée
- emmaus solidarité pour une association
=> add private organization and association to yopmail domain email

cypress/e2e/join_with_code_sent_to_official_contact_email.cy.js, cypress/e2e/join_with_code_sent_to_official_educ_nat_contact_email.cy.js, src/controllers/user/official-contact-email-verification.ts, src/services/organization.ts, src/views/user/official-contact-email-verification.ejs
</p>
---
\from @Anais-Tailhade 
---
Closes https://github.com/betagouv/moncomptepro/issues/465
=> fix(views): remplace mairie by établissement scolaire

installation.md
A bit nitpicky here but I feel like having a "Testing the Application" heading to talk about the local app url and login info is a bit misleading. As I was just quickly scanning the docs via headings I actually skipped this part at first thinking "I don't need to worry about tests right now".
=> chore: rephrase install doc to prevent confusions with actual *tests*

src/connectors/brevo.ts, src/views/help.ejs
The sender's email should be shorter than 46 characters to ensure that the "envelope-from" does not exceed 64 characters, thereby preventing the email address format from becoming invalid.
=> feat: shorten sender email

src/services/get-notifications-from-request.ts
For an unknown reason, there are still occurrences where calls made with query param 'notification=session_expired' are causing errors. We aim to prevent these errors from triggering alerts in Sentry.
=> chore: remove useless sentry error

.github/dependabot.yml
</p>
---
Allow bots to update the dependencies on the repo.
@rdubigny If you feel ready. npm dependencies can be updated to ;)
```yaml
- package-ecosystem: "npm"
directory: "/"
labels:
- dependencies
schedule:
interval: "weekly"
```
=> chore(dependabot): add weekly bot updates

.github/workflows/end-to-end.yml, .github/workflows/fixtures.yml, .github/workflows/test.yml
The Ci is in recent PRs is strangely broken. 
This PR is testing if it's related to the latest commit.
---
Reverts betagouv/moncomptepro#542
=> Revert "ci(github): bump ubuntu to 22.04"

src/views/partials/footer.ejs
The address of the official government site has changed and the SIG has asked us to update the footer links.
=> RD: replace gouvernement.fr by info.gouv.fr

src/index.ts
</p>
---
Set the APM to 10% with a 20% of transactions sent.
\from https://docs.sentry.io/platforms/javascript/profiling/
> Set profilesSampleRate to 1.0 to profile every transaction.  
Since profilesSampleRate is relative to tracesSampleRate, the final profiling rate can be computed as tracesSampleRate * profilesSampleRate
=> perf(sentry): bring down the sample rate

src/controllers/interaction.ts
The ENABLE_FIXED_ACR option, when set to true, previously caused an infinite redirection loop if acr mfa was required.
Changes:
- ENABLE_FIXED_ACR now enforces eIDAS1 acr even if mfa acr has been satisfied.
- This implementation does not comply with the OpenID specification.
- This adjustment ensures compatibility with AgentConnect without breaking the use of mfa acr.
=> fix: Infinite Redirection Loop for ENABLE_FIXED_ACR

src/connectors/api-annuaire-service-public.ts, src/connectors/test.ts, test/api-annuaire-service-public-data/invalid-cog.json, test/api-annuaire-service-public-data/one-mairie.json, test/api-annuaire-service-public-data/two-mairies.json, test/api-annuaire-service-public.test.ts
The data model is not the same. I tried to adapt the TypeScript type. 
The ‘zoning/municipalities’ entry does not exist in this dataset.
To do : 
</p>
=> RD: update API and type TS

cypress/fixtures/delete_account.sql
fix : delete column "verified_email_domains" of relation "organizations" because it dosnt exists
=> RD: delete column SQL file in delete_account

src/connectors/brevo.ts, src/controllers/user/verify-email.ts, src/middlewares/user.ts, tsconfig.json
=> chore(tsc): add noUnusedLocals option

src/config/env.zod.ts
Kind of a hot fix to allow the sandbox deployed instance to word :bow:
=> :wrench: allow sandbox as DEPLOY_ENV

src/controllers/user/signin-signup.ts, src/controllers/webauthn.ts, src/managers/session/unauthenticated.ts, src/managers/user.ts, src/types/express-session.d.ts, src/views/user/sign-in.ejs
This PR hide the option to login with passkey if the user has not configured it.
Without Passkey configured:
With Passkey configured:
=> feat: hide keypass button if not configured

cypress/e2e/activate_totp/index.cy.ts, cypress/e2e/delete_totp/index.cy.ts, src/views/connection-and-account.ejs
=> Ds feedback

src/views/partials/footer.ejs, src/views/partials/header.ejs
Première pull request qui renvoient les sections "aide" vers le helpdesk de crisp. 
Dans une seconde PR il faudra cleaner le code et supprimer la page aide interne (qui pour l'instant est encore nécessaire pour les parcours)
=> chore(link): replace intern help link with external crisp link

.github/workflows/test.yml, .gitignore, Dockerfile, package-lock.json, package.json, packages/email/.storybook/ChangeView.tsx, packages/email/.storybook/SendEmailFormWebComponent.tsx, packages/email/.storybook/index.html, packages/email/.storybook/index.tsx, packages/email/README.md, packages/email/index.html, packages/email/package.json, packages/email/src/DeleteFreeTotpMail.stories.tsx, packages/email/src/DeleteFreeTotpMail.tsx, packages/email/src/UpdatePersonalDataMail.stories.tsx, packages/email/src/UpdatePersonalDataMail.tsx, packages/email/src/_layout.tsx, packages/email/src/components/Html.tsx, packages/email/src/components/Link.tsx, packages/email/src/components/ProConnectLogo.tsx, packages/email/src/components/Section.tsx, packages/email/src/components/Text.tsx, packages/email/src/components/index.ts, packages/email/src/components/style.ts, packages/email/src/index.ts, packages/email/tsconfig.json, tsconfig.json
</div>
---
> Might be over kill but this is a proposition of ui dev environnement using the existing Vite dependency allowing us to audit in realtime the emails we are sending.
<details>
<summary>Why ?</summary>
> *Context*: We need to migrate Brevo templates to ProConnect 
Any approche on having emails on the code base have the following flaws:
- HTML template relay on the old web
- CSS styling is a mess
- One need external services to test templates across various email clients and devices
- Only widely supported fonts makes the text appears as intended
- Images should be hosted somewhere
Given :
- One can use famous frameworks to build email : https://mjml.io, https://get.foundation/emails.html, https://maizzle.com, etc...
- Most of them relay on a jsx like …
=> feat(email): storybook like email package

package.json
=> chore(pkg): allow unit test watch and reload

cypress/e2e/signin_with_magic_link/index.cy.ts, packages/email/src/MagicLink.stories.tsx, packages/email/src/MagicLink.tsx, packages/email/src/index.ts, src/connectors/brevo.ts, src/managers/user.ts
=> feat(email): add magic link smtp email

src/controllers/user/signin-signup.ts
=> fix(www): remove explicit catch of weak password on signup

migrations/1731434032350_delete-already-verified-email-domain.cjs
</div>
---
```sql
SELECT
COUNT(*)
FROM
email_domains
WHERE
verification_type IS NULL
AND (organization_id, DOMAIN) IN (
SELECT
organization_id,
DOMAIN
FROM
email_domains
GROUP BY
organization_id,
DOMAIN
HAVING
COUNT(
CASE
WHEN verification_type IS NULL THEN 1
END
) > 0
AND COUNT(
CASE
WHEN verification_type IS NOT NULL THEN 1
END
) > 0
);
```
And found **2285** entries to remove :eye: (12/11/2024)
=> feat(database): remove already verified domain email

src/middlewares/user.ts
With @douglasduteil, we discovered an error loop. When the confirmation email isn't sent, you can't go back because a session is created but the user doesn't exist. This PR allows you to delete the session when you go back!
=> fix(authent): add destroy session when user dosnt exists to avoid error

package-lock.json, package.json
Bumps [send](https://github.com/pillarjs/send) to 0.19.0 and updates ancestor dependency [@gouvfr/dsfr](https://github.com/GouvernementFR/dsfr). These dependencies need to be updated together.
Updates `send` from 0.16.2 to 0.19.0
- [Release notes](https://github.com/pillarjs/send/releases)
- [Changelog](https://github.com/pillarjs/send/blob/master/HISTORY.md)
- [Commits](https://github.com/pillarjs/send/compare/0.16.2...0.19.0)
Updates `@gouvfr/dsfr` from 1.12.1 to 1.13.0
- [Release notes](https://github.com/GouvernementFR/dsfr/releases)
- [Changelog](https://github.com/GouvernementFR/dsfr/blob/main/CHANGELOG.md)
- [Commits](https://github.com/GouvernementFR/dsfr/compare/v1.12.1...v1.13.0)
---
updated-dependencies:
- dependency-name: send dependency-type: indirect
- dependency-name: …
=> chore(deps): bump send and @gouvfr/dsfr

Dockerfile, package-lock.json, package.json, packages/core/tsconfig.json, packages/crisp/tsconfig.json, packages/debounce/package.json, packages/debounce/src/api/single-validation.ts, packages/debounce/tsconfig.json, packages/devtools/typescript/base/tsconfig.json, packages/devtools/typescript/package.json, packages/email/tsconfig.json, packages/identite/tsconfig.json, packages/insee/src/formatters/libelle-from-code-effectif.ts, packages/insee/tsconfig.json, tsconfig.json
=> chore(devtools): add shared typescript config

cypress/e2e/join_with_code_sent_to_official_contact_email/index.cy.ts, cypress/e2e/join_with_code_sent_to_official_educ_nat_contact_email/index.cy.ts, src/views/user/join-organization-confirm.ejs, src/views/user/official-contact-email-verification.ejs
avant la campagne du FS de l'Apostille :
Page de confirm d'utilisation d'un email perso : 
- supression de l'affichage inline
- passage du btn "corriger" en primary
- 
Page de vérif d'email officiel
- met à jour des wordings  
- met à jour le lien de l'annuaire des services publics
- déplace le banner info avant le btn retour
=> update wording on the official email verif page

docker-compose.yml
It's somehow a fix has the default healthcheck seems to fail with network_mode: "host"
=> chore(docker): add maildev healthcheck

packages/identite/src/managers/franceconnect/openid-client.ts
Reverts numerique-gouv/proconnect-identite#1101
---
Because `Erreur Y030007` 
in preprod :(
=> Revert "feat(franceconnect): force reauth"

.github/workflows/release.yml
Will be useful for separating the external and internal package use
\see https://pnpm.io/package_json#publishconfig
=> ci(release): use pnpm to publish packages

packages/email/src/components/ProConnectLogo.tsx
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExa2pncXZpbGJodTJrMXFoMmM5ZmNmczAxY2ppaWM5Y3U5MTU4ZW9tdyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/FBJHTakvaHY6Q/giphy.gif"></p>
=> a11y(logo): removes the ‘logo’ specification from art

src/config/errors.ts, src/connectors/api-annuaire-service-public.ts
<div align=center>
</div>
---
Following a recursing Sentry error, https://errors.data.gouv.fr/organizations/sentry/issues/139005/ I start guessing that our problems with Maires comes from emails in the Annuaire Api flagged invalid by use.
This changes will help us read that info on Sentry
=> ✨ feat: more info on Annuaire Api Errors

packages/testing/README.md
---
Documents the @packages/testing mock server and CLI tools for ProConnect integrations. Includes detailed usage examples, endpoint descriptions, CLI workflows, and discovery interface links for browsing test data.
Helps developers understand how to use the testing infrastructure for reliable integration testing without external API dependencies.
=> 📝 add comprehensive README for testing package

cypress/e2e/join_org_with_rejected_moderation/fixtures.sql, cypress/e2e/join_org_with_rejected_moderation/index.cy.ts, src/services/moderation.test.ts, src/services/moderation.ts
When extracting rejection reasons from moderation comments, the function now returns a default reason ("Raison non spécifiée") instead of the original comment when the standard format is not found. This prevents potential exposure of moderator identities.
=> 🔒 fix(moderation): return default reason instead of exposing moderator identity

.changeset/free-bushes-stay.md
<div align=center><img src="https://media0.giphy.com/media/v1.Y2lkPWVjMTJjNzA0emFvNHh0YzM4d3k3MmttZ2VveDZnMHViN2czbmJmOGtvbHFhZHc5eCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/7J4P7cUur2DlErijp3/giphy.gif" /></div>
---
Corrige le nom du package dans le changeset `free-bushes-stay.md` pour utiliser le namespace officiel `@proconnect-gouv` au lieu de l'ancien `@gouvfr-lasuite`.
**Problème résolu :**
```
🦋  error Error: Found changeset free-bushes-stay for package @gouvfr-lasuite/proconnect.identite which is not in the workspace
```
**Changements :**
- Mise à jour du package name de `@gouvfr-lasuite/proconnect.identite` vers `@proconnect-gouv/proconnect.identite`
- Correction de l'import dans l'exemple de code
=> fix(changeset): 🔧 correct package name from @gouvfr-lasuite to @proconnect-gouv
